version: "3.3"
services:
  antidote1:
     image: antidotedb/antidote:latest
     container_name: antidote1
     environment:
       NODE_NAME: "antidote@antidote1"
       SHORT_NAME: "true"
     cap_add:
       - NET_ADMIN
     networks:
       - interdc
       - local1

  antidote2:
    image: antidotedb/antidote:latest
    container_name: antidote2
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    cap_add:
      - NET_ADMIN
    networks:
      - interdc
      - local2

  antidote-notebook:
    image: antidotedb/notebook:latest
    container_name: antidote_notebook
    ports:
      - "8888:8888"
    cap_add:
      - NET_ADMIN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local1
      - local2

networks:
  interdc:
  local1:
  local2:
